Import('env', 'ptylib')
 
proxy_test_env = env.Clone()
proxy_test_env.Append(CPPPATH="#src/gdterm/pty")
proxy_test = proxy_test_env.Program(target="proxy_test", source="proxy_test.cpp", LIB=ptylib)
 
Return("proxy_test")
