Import('env', 'ptylib')
 
proxy_test_env = env.Clone()
proxy_test_env.Append(CPPDEFINES = "FORCE_UTF8")
proxy_test_env.Append(CPPPATH="#src/gdterm/pty")
proxy_test = proxy_test_env.Program(target="proxy_test", source="proxy_test.cpp", LIB=ptylib)
 
show_options_env = env.Clone()
show_options = show_options_env.Program("show_options.cpp")

tmt_test_env = env.Clone()
if env["platform"] == "windows":
	tmt_test_env.Append(CXXFLAGS="/utf-8")
tmt_test_env.Append(CPPDEFINES = "FORCE_UTF8")
tmt_test_env.Append(CPPPATH="#src/gdterm/pty/thirdparty")
tmt_test = tmt_test_env.Program(target="tmt_test", source="tmt_test.cpp", LIB=ptylib)

utf8_to_unicode = tmt_test_env.Program(target="utf8_to_unicode", source="utf8_to_unicode.cpp", LIB=ptylib)

Return("proxy_test", "show_options", "tmt_test", "utf8_to_unicode")
