Import('env', 'name', 'ptylib')

env.Append(CPPPATH="pty")
env.Append(CPPPATH="pty/thirdparty")
env.Append(LIBS=ptylib)

sources = Glob("*.cpp")

if env["platform"] == "macos":
	env.Append(CPPDEFINES = "USE_COMMAND_KEY_FOR_SHORTCUT")

library = env.SharedLibrary(name, source=sources)

Return("library")
